app/Services/DataPersistence/ServicePersistenceService.php
tests/Feature/ServicesTest.php

https://app.shortcut.com/connectedplaces/story/2336/auto-disable-services-after-a-specific-date
- Fixed handling of ISO8601 end dates when creating service

Fixed handling of end dates when creating new services

---

app/Docs/OpenApi.php
app/Docs/Operations/Services/DisableStaleServiceOperation.php
app/Docs/Paths/Services/ServicesDisableStalePath.php
app/Docs/Schemas/Service/DisableStaleServiceSchema.php
app/Docs/Schemas/Service/RefreshServiceSchema.php
app/Http/Controllers/Core/V1/Service/DisableStaleController.php
app/Http/Controllers/Core/V1/Service/RefreshController.php
app/Http/Controllers/Core/V1/ServiceController.php
app/Http/Requests/Service/DisableStale/UpdateRequest.php
app/Http/Requests/Service/Refresh/UpdateRequest.php
routes/api.php
tests/Feature/ServicesTest.php

https://app.shortcut.com/connectedplaces/story/2338/data-freshness
- Sort services by last modified at https://github.com/the-leeds-repo/api/pull/24
- Service admins can refresh service without token https://github.com/the-leeds-repo/api/pull/32/
- Bulk disable services https://github.com/the-leeds-repo/api/pull/33/

Stuartlaverick/sc 2338/data freshness

---

app/Http/Requests/Search/Pages/Request.php
app/Http/Requests/Search/Request.php

https://app.shortcut.com/connectedplaces/story/2428/bug-bugfix-prevent-pagination-parameters-being-passed-as-string
- Cherry picked https://github.com/LondonBoroughSutton/suttoninformationhub-api/pull/12/commits/d5fb29e3d53616e9e843c75ae1145a303fa26c9d

Cherry pick d5fb29e3d53616e9e843c75ae1145a303fa26c9d and refactor

---

resources/assets/sass/app.scss
resources/views/layout.blade.php
resources/views/partials/environment-warning.blade.php

https://app.shortcut.com/connectedplaces/story/2424/staging-warning-banner
- Cherry pick from https://github.com/LondonBoroughSutton/suttoninformationhub-api/pull/25/commits/b6284a19f98836974dee0ede2e8a44a8987bbf1b

Cherry pick b6284a19f98836974dee0ede2e8a44a8987bbf1b and refactor

---

tests/Feature/OrganisationsTest.php
tests/Feature/ServicesTest.php
tests/Feature/UsersTest.php

https://app.shortcut.com/connectedplaces/story/2431/added-additional-tests-for-global-admin-permissions
- Cherry pick https://github.com/LondonBoroughSutton/suttoninformationhub-api/pull/28/commits/e115b970c2745e606aec3050e9ee1eeedb5306bd

Added additional tests for global admin permissions

---

app/Http/Controllers/Core/V1/SearchController.php
app/Search/ElasticsearchServiceSearch.php
tests/Feature/SearchServiceTest.php
tests/Unit/Models/ReportTest.php

https://app.shortcut.com/connectedplaces/story/2417/search-within-collections
- Imported changeset https://github.com/Healthy-London-Partnership/api/pull/37 to allow services search to include multiple categories and personas

Import search within collections for services

---

app/Search/ElasticSearch/ServiceEloquentMapper.php
tests/Feature/Search/ServiceTest.php

- The service objects returned from a search did not include the `service_locations` property which caused the frontend code to error as it expected this property
- Relationship `serviceLocations` is lazily loaded during the search request and included in the returned objects

Service search includes service_locations in returned objects

---

database/migrations/2022_11_30_104455_update_services_add_cqc_location_id_field.php
database/migrations/2023_08_25_145454_update_collection_page_add_on_delete_cascade.php
tests/Feature/PagesTest.php

https://app.shortcut.com/helpyourselfsutton/story/2763/unable-to-delete-a-page
- The page was unable to be deleted due to the collection relationships in place
- A migration has been added to add on delete cascade to the page collection relationship

Updated page collection relationship add ondelete cascade

---

app/Http/Controllers/Core/V1/UserController.php
app/Http/Requests/Page/DestroyRequest.php
app/Http/Requests/Page/ShowRequest.php
app/Http/Requests/Page/StoreRequest.php
app/Http/Requests/Page/UpdateRequest.php
app/Http/Requests/User/UpdateRequest.php
app/Listeners/Notifications/UserRolesUpdated.php
app/Models/Role.php
app/Models/User.php
app/Models/UserRole.php
app/Providers/AppServiceProvider.php
app/Providers/TelescopeServiceProvider.php
app/Rules/CanAssignRoleToUser.php
app/Rules/UserHasRole.php
composer.json
composer.lock
config/app.php
config/telescope.php
database/migrations/2023_08_29_105145_seed_content_admin_role_data.php
tests/Feature/PagesTest.php
tests/Feature/UsersTest.php

https://app.shortcut.com/helpyourselfsutton/story/2754/create-a-new-content-admin-user-role
- Created new role 'Content Admin'
- Only Global Admin can create Content Admin
- Only Content admin and Super Admin can create, update and delete pages
- All users and guest can view pages

Sutton sc 2754 create a new content admin user role

---

app/Docs/Operations/OrganisationEvents/DestroyOrganisationEventOperation.php
app/Http/Requests/OrganisationEvent/DestroyRequest.php
tests/Feature/OrganisationEventsTest.php

https://app.shortcut.com/helpyourselfsutton/story/2773/update-user-permissions-api
- Updated delete event permissions. Remove organisation admin and global admin. Only super admin.

Updated permissions delete event only super admin

---

app/Docs/Operations/UpdateRequests/ShowUpdateRequestOperation.php
app/Http/Requests/UpdateRequest/ShowRequest.php
app/Search/ElasticSearch/ServiceQueryBuilder.php
tests/Feature/UpdateRequestsTest.php

https://app.shortcut.com/helpyourselfsutton/story/2773/update-user-permissions-api
- Allow all users who can create update requests to view update request singular

Allow service admin and up to view update request

---

.env.example
app/Providers/RouteServiceProvider.php
config/local.php
tests/Feature/PagesTest.php

https://app.shortcut.com/connectedplaces/story/3377/api-rate-limits
- Moved api request rate limit into config key "local.api_rate_limit" that is based on environment variable "API_RATE_LIMIT"
- Set default rate limit to 300 request per minute per user / IP

Moved rate limit to config and increased default

---

.env.example
app/EmailSenders/GovNotifyEmailSender.php
app/EmailSenders/LogEmailSender.php
app/EmailSenders/MailgunEmailSender.php
app/Http/Requests/Referral/StoreRequest.php
app/Models/Notification.php
app/Providers/AppServiceProvider.php
app/Providers/TwilioServiceProvider.php
app/Rules/UkMobilePhoneNumber.php
app/SmsSenders/GovNotifySmsSender.php
app/SmsSenders/LogSmsSender.php
app/SmsSenders/TwilioSmsSender.php
lang/en/sms.php

https://app.shortcut.com/connectedplaces/story/3376/twilio-and-mailgun-integrations-are-not-working
- Updated AppServiceProvider to use new config key for mail sender
- Updated Mailgun integration
- Updated Twilio integration
- Updated UkMobilePhoneNumber Rule to accept either '07' numbers or '+447' numbers

Resolved issues with mailgun and twilio integrations

---

.env.example
app/Providers/GovNotifyServiceProvider.php

https://app.shortcut.com/connectedplaces/story/3557/notifications-on-staging-are-not-working-with-gov-notify
- Updated version of Guzzle Http Client to use to 7.x

Updated working version of Guzzle Http Client to 7.x

---

app/Providers/AuthServiceProvider.php
routes/passport.php
tests/Feature/PagesTest.php

https://app.shortcut.com/connectedplaces/story/3414/status-field-is-not-being-honored-for-new-pages
- Added test to check status update on Page was being honoured by update request
- Added explicit binding for StatefulGuard for AuthorizationController to AuthProvider

Added explicit binding for StatefulGuard for AuthorizationController

---

app/Models/File.php

https://app.shortcut.com/connectedplaces/story/3594/reports-don-t-seem-to-be-downloading-anymore
- Report downloads were failing as the `Content-Disposition` header was being hidden by the default CORS policy
- Added `'Access-Control-Expose-Headers' => ['Content-Type', 'Content-Disposition']` header to file http responses which will prevent the header being hidden

Added Access-Control-Expose-Headers header to file response

---

.env.example
docker/app/Dockerfile

https://app.shortcut.com/connectedplaces/story/3370/deploy-updated-api-to-new-env
- Laravel sqsQueue driver altered the way it built AWS SQS Queue URLs and was inserting a trailing slash before the word default, causing requests to AWS SQS Queues to fail.
- The way the SQS_PREFIX and SQS_QUEUE environment variables are stored is now different and is documented in `.env.example`

Update env.example with instructions for SQS Queue

---

.env.example
.gitignore
app/Http/Controllers/Core/V1/PageController.php
tests/Feature/PagesTest.php

https://app.shortcut.com/connectedplaces/story/3626/pages-side-nav-menu-missing
- Pages index include `landingPageAncestors` had at some point been changed to `landing_page_ancestors` but the docs were not updated, so calls with the `landingPageAncestors` include were failing
- It was decided to revert to `landingPageAncestors` as this is consistent with the docs

Changed the name of the index page includes to match the docs

---

.env.example
app/Models/Collection.php
app/Models/CollectionTaxonomy.php
app/Models/Location.php
app/Models/Organisation.php
app/Models/Taxonomy.php
config/scout.php
tests/Unit/Models/CollectionTest.php

https://app.shortcut.com/connectedplaces/story/3633/fix-collection-reindex-issue
- updated all the touchServices methods to use the `searchable` method
- updated `Collection::syncCollectionTaxonomies` so services and events are re-indexed if their taxonomies are added or removed from a collection

Added reindexing for services and events to collection syncTaxonomies

---

app/Http/Requests/OrganisationSignUpForm/StoreRequest.php
app/Rules/UkPhoneNumber.php

https://app.shortcut.com/connectedplaces/story/3647/update-request-won-t-approve-due-to-phone-number-validation-issue
- Added 0800 numbers to valid UK phone number regex
- Added pre-validation method to strip spaces from phone numbers

Updated UK phone regex and stripped spaces

---

app/Models/Page.php
app/Search/ElasticSearch/CollectionCategoryQueryBuilder.php
app/Search/ElasticSearch/CollectionPersonaQueryBuilder.php
app/Search/ElasticSearch/ServiceQueryBuilder.php
database/factories/ServiceFactory.php
tests/Feature/Search/ServiceTest.php

https://app.shortcut.com/connectedplaces/story/3659/improve-sutton-search-results
- When searching for a persona there were no service results being returned
- The search score function was creating an error if the service had no score search attribute
- Updated the score function to handle results with no score

Improved score function for service search

---

app/Docs/Schemas/Service/UpdateServiceSchema.php
app/Models/Service.php
tests/Feature/ServicesTest.php

https://app.shortcut.com/connectedplaces/story/3648/admin-ui-hangs-when-trying-to-change-the-orgniasation-value-on-a-service
- Updating a service and changing the organisation returned the organisation id but not the organisation object
- Added the organisation object to the update response if the organisation id was being changed

Added organisation to service update response if organisation changed

---

app/Models/Scopes/UserScopes.php

https://app.shortcut.com/connectedplaces/story/3650/filtering-by-permission-level-does-not-work
- Updated ordering SQL for highest permission level

Bug/sc 3650/filtering by permission level does not work

---

app/Docs/Operations/UpdateRequests/IndexUpdateRequestOperation.php
app/Http/Controllers/Core/V1/UpdateRequestController.php
app/Http/Filters/UpdateRequest/TypeFilter.php
tests/Feature/UpdateRequestsTest.php

https://app.shortcut.com/connectedplaces/story/3745/filter-update-requests-by-entity-type
- Added filter to update request index to filter results by `updateable_type`

Added updateable_type filter to update request index

---

app/Http/Requests/OrganisationEvent/UpdateRequest.php
tests/Feature/PagesTest.php

https://app.shortcut.com/connectedplaces/story/3332/remove-validation-from-events-so-start-date-can-be-in-the-past
- Updated validation on `OrganisationEvent\UpdateRequest` to allow `start_date` to be in the past, but `end_date` must be on or after today

Changed validation on update request to allow past start dates

---

app/Search/ElasticSearch/ServiceEloquentMapper.php
tests/Feature/Search/ServiceTest.php
tests/Feature/ServicesTest.php

https://app.shortcut.com/connectedplaces/story/3708/maps-view-is-not-loading-on-search-results
- `Search\ServiceEloquentMapper` was loading the `serviceLocations` relationship
- Changed the relationship loading to `serviceLocations.location` so loading the `location` object

Fixed search ServiceEloquentMapper relationships loading

---

app/Models/Page.php
app/Rules/PageContent.php
tests/Feature/PagesTest.php

https://app.shortcut.com/connectedplaces/story/3308/allow-videos-to-be-embeded-within-page-content
- Added `video` content type for Page `content` field

Added video content type tpo page content

---

tests/Feature/UpdateRequestsTest.php

https://app.shortcut.com/connectedplaces/story/3754/freshness-emails-being-sent-incorrectly
- Test to check the updating a service via an update request will also update the `last_modified_at` field so preventing the sending of email reminders about service freshness

Added test that updating service with update request updates last_modified_at

---

app/Docs/ExternalDocs.php
app/Docs/Info.php
app/Docs/OpenApi.php
resources/views/layout.blade.php

https://app.shortcut.com/connectedplaces/story/2319/add-powered-by-tag-line-to-footer-of-admin-and-api
- Added 'Powered by Ayup Connect' link to footer
- Removed Github wiki link from docs header
- Added 'Powered by Ayup Connect' link to docs header

Added Powered by Ayup Connect to footer and header of docs

---

app/Http/Requests/Organisation/UpdateRequest.php
app/Http/Requests/OrganisationSignUpForm/StoreRequest.php
tests/Feature/OrganisationsTest.php

https://app.shortcut.com/connectedplaces/story/3941/org-phone-required-on-public-registration
- Removed requirement for either an email or phone field on organisation registration workflow

Remove requirement for email or phone on organisations

---

app/Http/Requests/Organisation/StoreRequest.php
app/Http/Requests/Organisation/UpdateRequest.php
app/Http/Requests/OrganisationEvent/StoreRequest.php
app/Http/Requests/OrganisationEvent/UpdateRequest.php
app/Http/Requests/OrganisationSignUpForm/StoreRequest.php

https://app.shortcut.com/connectedplaces/story/4099/increase-event-description-char-limit-to-10k
- Set limit for organisation description to 10000 characters
- Set limit for organisation event description to 10000 characters
- Set limit for service description to 3000 characters

Set text limits on all the description fields

---

app/Docs/Schemas/Page/PageListItemSchema.php
app/Docs/Schemas/Page/PageSchema.php
app/Http/Controllers/Core/V1/PageController.php
app/Http/Resources/PageResource.php
database/factories/PageFactory.php
tests/Feature/PagesTest.php

https://app.shortcut.com/connectedplaces/story/4090/add-in-breadcrumbs-data-to-api-endpoint-for-pages-slug
- Refactored `PageResource`
- Reduced size of relationship entities `parent`, `landing_page` and `children`
- Added new relationship `ancestors` with a list of ancestors in descending order from root down suitable for breadcrumbs
- Added new `include=ancestors` option for the pages index api to include the ancestors relationship on all page result items

Refactored page resource, added ancestors key

---

.env.example
app/Models/Relationships/PageRelationships.php
app/Observers/PageObserver.php
app/Observers/UpdateRequestObserver.php
tests/Feature/PagesTest.php

https://app.shortcut.com/connectedplaces/story/4414/bug-update-requests-corrupt-when-multiple-update-requests-are-made
https://app.shortcut.com/connectedplaces/story/4415/bug-update-requests-return-500-when-entity-has-been-deleted
- Orphan update requests for pages were left when a page was deleted
- `PageObserver::deleting` method removes orphan update requests
- `UpdateRequestObserver::created` method removed duplicate data keys from other update requests for the same entity. Due to the JSON format of a Page content field this was leaving empty nodes in the Page content data.
- `UpdateRequestObserver::created` method removes the whole content key from any previous Page update request if a new update request for the same entity is also updating the content
If there are any actions that …

Bug/sc 4414/bug update requests corrupt when multiple

---

app/Models/Page.php
app/Models/Relationships/PageRelationships.php
app/Observers/OrganisationEventObserver.php
app/Providers/ModelServiceProvider.php
tests/Feature/LocationsTest.php
tests/Feature/OrganisationEventsTest.php
tests/Feature/OrganisationsTest.php
tests/Feature/PagesTest.php

https://app.shortcut.com/connectedplaces/story/4012/remove-outstanding-update-requests-when-entities-are-deleted
- Added tests to check that outstanding update requests for organisations, services, events, pages and locations are deleted when the entity is deleted
- Added functionality to delete outstanding update requests on deletion to pages and events

All entities will delete update requests when they are deleted

---

app/Http/Controllers/Core/V1/UpdateRequest/ApproveController.php
app/Models/UpdateRequest.php
app/Rules/PageContent.php
app/UpdateRequest/NewOrganisationCreatedByGlobalAdmin.php
app/UpdateRequest/NewOrganisationEventCreatedByOrgAdmin.php
app/UpdateRequest/NewPage.php
app/UpdateRequest/NewServiceCreatedByGlobalAdmin.php
app/UpdateRequest/NewServiceCreatedByOrgAdmin.php
tests/Feature/UpdateRequestsTest.php

https://app.shortcut.com/connectedplaces/story/3307/add-new-approve-and-edit-button-to-update-requests
- Update requests for new entities should return the new entity ID once it is created

Add updateable ID to update request for new entity

---

app/Docs/Paths/UpdateRequests/UpdateRequestsApprovePath.php
app/Http/Controllers/Core/V1/UpdateRequest/ApproveController.php
tests/Feature/UpdateRequestsTest.php

https://app.shortcut.com/connectedplaces/story/3307/add-new-approve-and-edit-button-to-update-requests
- Added a flag to the update request approve endpoint to indicate if this is an 'approve' or 'approve and edit' submission
- Pages and services will be disabled if the submission is 'approve and edit'

Disable service or page when action edit flag is passed to approve

---

app/Docs/Schemas/ServiceLocation/ServiceLocationSchema.php
app/Http/Resources/ServiceLocationResource.php
app/Models/HolidayOpeningHour.php
app/Models/RegularOpeningHour.php
app/Models/ServiceLocation.php
tests/Feature/ServiceLocationsTest.php

https://app.shortcut.com/connectedplaces/story/3396/introduce-a-next-occurs-to-the-service-schema
- Added `next_occurs` property to each `ServiceLocation` on a `Service` `service_locations` property
- Each `next_occurs` property has a `date`, `start_time` and `end_time`

Feature/sc 3396/introduce a next occurs to the service schema

---

database/migrations/2024_08_01_140913_update_update_requests_increase_message_field_size.php

https://app.shortcut.com/connectedplaces/story/4543/update-request-rejection-error
- Added migration to increase `update_requests.rejection_message` from 100 to 1000 characters

Add migration to increase size of update request message field

---

.env.example
app/Http/Requests/Service/StoreRequest.php
app/Http/Requests/Service/UpdateRequest.php
config/local.php
tests/Feature/ServicesTest.php

https://app.shortcut.com/connectedplaces/story/4547/enforce-a-max-limit-on-the-number-of-gallery-items-for-services
- Added `max` rule `gallery_images` array field on store service
- Added `max` rule `gallery_images` array field on update service
- Added `.env` variable `SERVICE_MAX_GALLERY_IMAGES` which defaults to 5

Added max length validation rule for gallery images

---

app/Rules/UkPhoneNumber.php
tests/Unit/Rules/UkPhoneNumberTest.php

https://ayup.atlassian.net/jira/software/projects/ACD/boards/8?selectedIssue=ACD-418
Refined the UK phone number regex to handle various valid formats, including mobile, landline, and short six-digit numbers. Added comprehensive unit tests to ensure the rule correctly validates or rejects different cases.

Add improved UK phone number validation and unit tests

---

app/Http/Controllers/Core/V1/CollectionOrganisationEventController.php
app/Http/Requests/CollectionOrganisationEvent/StoreRequest.php
app/Http/Requests/CollectionOrganisationEvent/UpdateRequest.php

https://ayup.atlassian.net/jira/software/projects/ACD/boards/8?selectedIssue=ACD-416&sprintStarted=true
Allow `image_file_id` to be nullable in `StoreRequest` and `UpdateRequest` validation rules. Adjust logic in the controller to handle cases where `image_file_id` is explicitly null. This ensures greater flexibility for handling optional image uploads.

Make `image_file_id` nullable in requests and update logic.
