AyupDigital/api

- app/Rules/Password.php
https://app.shortcut.com/connectedplaces/story/2425/bug-user-password-bug-with-characters
- Removed single and double quotes from allowed password characters
> Removed single and double quotes from allowed password characters

- app/Console/Commands/Ck/CreateUserCommand.php
https://app.shortcut.com/connectedplaces/story/2342/bulk-import-services-organisations
- Allow add user command to set the users password
> Create user command now allows password to be set

- app/Http/Controllers/SitemapController.php
- routes/web.php
- tests/Feature/SitemapTest.php
https://app.shortcut.com/connectedplaces/story/2429/xml-sitemap
- Update XML Sitemap
- Cherry picked from https://github.com/LondonBoroughSutton/suttoninformationhub-api/pull/27 and https://github.com/LondonBoroughSutton/suttoninformationhub-api/pull/37
> Stuartlaverick/sc 2429/xml sitemap

- resources/views/partials/environment-warning.blade.php
https://app.shortcut.com/connectedplaces/story/2459/update-hyerplink-in-staging-warning-banner
- Change the staging warning banner link to use the app url from the .env file
> Stuartlaverick/sc 2459/update hyerplink in staging warning banner

- .env.example
- app/Models/File.php
- config/filesystems.php
- tests/Feature/FilesTest.php
- Files not saving on s3 uploads bucket
- Forced files to use visibility private
- Changed config to throw exception if files not saved
> Forced file visibility to private on s3

- .env.example
- app/Models/File.php
- composer.json
- composer.lock
- config/redis.php
- package-lock.json
- package.json
> Installed predis/predis. Updated packages

- .env.example
- app/Emails/Email.php
- app/Models/Relationships/ServiceRelationships.php
- app/Sms/Sms.php
- config/queue.php
- database/migrations/2021_06_04_140343_add_lga_standards_top_level_category_taxonomy_to_taxonomies_table.php
- database/migrations/2021_06_13_121848_create_open_active_taxonomy_top_level_parent.php
- database/migrations/2022_07_06_134340_find_page_id_urls_and_replace_with_page_slug_urls.php
- tests/Feature/Auth/ForgotPasswordTest.php
- tests/Feature/Auth/LoginTest.php
- tests/Feature/ServicesTest.php
- tests/Unit/Console/Commands/Ck/CreateScheduledReportsCommandTest.php
- tests/Unit/Console/Commands/Ck/Notify/StaleServicesCommandTest.php
- tests/Unit/Console/Commands/Ck/Notify/StillUnactionedReferralsCommandTest.php
- tests/Unit/Console/Commands/Ck/Notify/UnactionedReferralsCommandTest.php
- tests/Unit/Listeners/Notifications/PageFeedbackReceivedTest.php
- tests/Unit/Listeners/Notifications/ReferralCompletedTest.php
- tests/Unit/Listeners/Notifications/ReferralCreatedTest.php
- tests/Unit/Listeners/Notifications/ReferralIncompletedTest.php
- tests/Unit/Listeners/Notifications/ServiceCreatedTest.php
- tests/Unit/Listeners/Notifications/UpdateRequestApprovedTest.php
- tests/Unit/Listeners/Notifications/UpdateRequestRejectedTest.php
- tests/Unit/Listeners/Notifications/UserCreatedTest.php
- tests/Unit/Listeners/Notifications/UserRolesUpdatedTest.php
- tests/Unit/Observers/ServiceObserverTest.php
- tests/Unit/Observers/UpdateRequestObserverTest.php
https://app.shortcut.com/helpyourselfsutton/story/2726/review-api-branches-and-consolidate
- Reviewed work carried out on suttoninformationhub.org.uk and carried over anything that was of general use
> Sutton sc 2726 review api branches and consolidate

- app/Rules/Postcode.php
https://app.shortcut.com/helpyourselfsutton/story/2757/creating-a-new-location-within-a-service-returns-an-accessible-toilet-error
- Updated the postcode rule regex following reading a discussion of the current UK gov regex here https://stackoverflow.com/a/51885364/709923
> Updated postcode regex

- app/Http/Requests/OrganisationSignUpForm/StoreRequest.php
- app/Http/Requests/User/StoreRequest.php
- app/Http/Requests/User/UpdateRequest.php
- app/Rules/UkMobilePhoneNumber.php
- bootstrap/helpers.php
- database/factories/UserFactory.php
- tests/Feature/OrganisationSignUpFormTest.php
- tests/Feature/UsersTest.php
https://app.shortcut.com/helpyourselfsutton/story/2739/introduce-stricter-validation-for-phone-numbers-on-the-user-entity
- Introduced new rule for mobile phone numbers
- Updated rule for general phone numbers
- Required users, whether on registration or in admin, to enter a mobile phone number
> Require users to have a mobile phone number

- app/Docs/Schemas/Setting/SettingSchema.php
- app/Docs/Schemas/Setting/UpdateSettingSchema.php
- app/Http/Controllers/Core/V1/SettingController.php
- app/Http/Requests/Setting/UpdateRequest.php
- database/migrations/2023_08_24_144038_add_accessibility_statement_page_to_cms_settings.php
- tests/Feature/SettingsTest.php
https://app.shortcut.com/helpyourselfsutton/story/2722/add-accessibility-page-within-cms-endpoint
- Added Accessibility Statement page to settings cms
> Added Accessibility Statement page to settings cms

- docker/app/Dockerfile
https://app.shortcut.com/connectedplaces/story/3370/deploy-updated-api-to-new-env
- Increased ulimit nofiles from 4096 to 40960
> Increased ulimit nofiles from 4096 to 40960

- .env.example
- aws/resources.py
- aws/variables.py
- package-lock.json
https://app.shortcut.com/connectedplaces/story/3611/update-sqs-queue
- Changed the pattern for the SQS queue name to `[name]-[UUID]-[environment]`
> Altered the SQS queue name format to work with sqs suffix

- .env.example
- app/Listeners/Notifications/UpdateRequestRejected.php
- config/local.php
- lang/en/emails/organisation.php
https://app.shortcut.com/connectedplaces/story/3599/notification-email-variables-not-parsing
- Updated placeholders in email language file
- Added config keys for T&C, Privacy and Accessibility page URIs
- Added frontend URI environment variable
> Fixed placeholders in email and added config keys for pages

- docker/app/Dockerfile
https://app.shortcut.com/connectedplaces/story/3611/update-sqs-queue
- Added `session required        pam_limits.so` to `/etc/pam.d/common-session-noninteractive`
> Updated Dockerfile to add ulimit fix to common-session-noninteractive

- app/Http/Requests/Referral/ShowRequest.php
- app/Models/User.php
- routes/api.php
https://app.shortcut.com/connectedplaces/story/3636/403-when-accessing-referrals
- Fixed permissions on referrals show
> Fixed permissions on viewing referrals

- .env.example
- app/Models/Scopes/UpdateRequestScopes.php
https://app.shortcut.com/connectedplaces/story/3652/update-request-invalid-type-bug
- Fixed update request entry for organisations created by global admins
> Fix update request entry for organisation created by global admin

- aws/resources.py
- config/local.php
- docker-compose.yml
- tests/Feature/UpdateRequestsTest.php
https://app.shortcut.com/connectedplaces/story/3750/upgrade-mysql-from-v5-7-to-v8-on-v2
- Updated Cloudformation template to use MySql version 8.0
> Upgrade MySql version to 8.0

- aws/cloudformation.py
- aws/conditions.py
- aws/parameters.py
- aws/resources.py
- aws/variables.py
https://app.shortcut.com/connectedplaces/story/3879/aws-waf-kingston-staging
- Added `AWS AWSManagedRulesCommonRuleSet` to the Cloudformation template
- Added `Fortinet all_rules` to the Cloudformation template
- Added parameter flags for each to allow them to be enabled or disabled
> Added AWS Web Application Firewall configuration to the Cloudformation template

- aws/resources.py
https://app.shortcut.com/connectedplaces/story/3879/aws-waf-kingston-staging
- Updated Cloudformation template, changed default action on all managed rule sets to Allow
> Feature/sc 3879/aws waf kingston staging

- app/Http/Filters/Organisation/HasPermissionFilter.php
- app/Http/Filters/OrganisationEvent/HasPermissionFilter.php
- app/Http/Filters/Service/HasPermissionFilter.php
- app/Http/Requests/Service/StoreRequest.php
- app/Http/Requests/Service/UpdateRequest.php
- aws/resources.py
https://app.shortcut.com/connectedplaces/story/3906/character-limit-on-good-to-know
- Fixed user permissions on `HasPermissionFilter` for `Service`, `Organisation` and `OrganisationEvent` allow Global and Super Admins to view all entities
- Set max characters for `UsefulInfo->description` to 1000
> Bug/sc 3906/character limit on good to know

- app/Docs/Operations/OrganisationEvents/IndexOrganisationEventOperation.php
- app/Http/Controllers/Core/V1/OrganisationEventController.php
- app/Models/Scopes/OrganisationEventScopes.php
- tests/Feature/OrganisationEventsTest.php
https://app.shortcut.com/connectedplaces/story/3339/add-accessible-toilet-filter-to-event-search
- Added `has_accessible_toilet` filter to `OrganisationEvent` index
> Add has_accessible_toilet filter to OrganisationEvent index

- app/Observers/ServiceObserver.php
- app/UpdateRequest/NewServiceCreatedByGlobalAdmin.php
- app/UpdateRequest/NewServiceCreatedByOrgAdmin.php
- tests/Feature/ServicesTest.php
https://app.shortcut.com/connectedplaces/story/4027/eligibility-not-updating
- Added processing of service eligibilities to the service and organisation update request workflow when creating a new service
> Add process service eligibilities to org admin create new service

- composer.json
- composer.lock
- docker/app/Dockerfile
https://app.shortcut.com/connectedplaces/story/4199/increase-ulimit
- Increased `ulimit` for open files from 40960 to 81920
> Increase ulimit in Dockerfile to 81920

- app/Http/Requests/Page/StoreRequest.php
https://app.shortcut.com/connectedplaces/story/4455/landing-page-multiple-submissions
- Improved error messages on page content
> Improved error messages on page content

- app/Http/Requests/Setting/UpdateRequest.php
> chore: fixed bug with missing optional

- app/Http/Requests/OrganisationEvent/UpdateRequest.php
> bug: removed strict booking validation on organisation events

- app/Http/Requests/OrganisationEvent/StoreRequest.php
- app/Http/Requests/OrganisationEvent/UpdateRequest.php
> bug: reduced intro limit on events to 255 from 300

- app/Http/Controllers/Core/V1/UpdateRequestController.php
> chore: updated update request controller

- app/Http/Controllers/Core/V1/Search/LocationController.php
- routes/api.php
- tests/Feature/Search/LocationsTest.php
> Added in new search endpoint for locations with relevant feature test

- app/Actions/StoreServiceLocationAction.php
- app/DataTransferObjects/ServiceLocationRequestObject.php
- app/Http/Controllers/Core/V1/ServiceLocationController.php
- app/Http/Requests/Service/StoreRequest.php
- app/Services/DataPersistence/ServicePersistenceService.php
- tests/Feature/ServicesTest.php
- tests/Unit/Actions/StoreServiceLocationActionTest.php
> chore: api changes

- app/Models/User.php
- tests/Unit/Models/UserTest.php
https://ayup.atlassian.net/jira/software/projects/ACD/boards/8?selectedIssue=ACD-433
> Acd 433 soft delete

- app/Http/Controllers/Core/V1/Search/LocationController.php
https://ayup.atlassian.net/jira/software/projects/ACD/boards/8?selectedIssue=ACD-431
> Added ordering by address_line_1 field
